Update old-gor.yml

diff --git a/.github/workflows/old-gor.yml b/.github/workflows/old-gor.yml
--- a/.github/workflows/old-gor.yml
+++ b/.github/workflows/old-gor.yml
@@ -66,31 +66,32 @@ jobs:
           HEALTH_TIMEOUT_SECONDS: '600'
         run: bash "${{ github.workspace }}/rpc/start-rpc.sh"
 
-      - run: yarn trade
+      - run: yarn unwrap:gor
+      # - run: yarn trade
 
-      - name: trades.json
-        run: cat temp/trades.json | jq
+      # - name: trades.json
+      #   run: cat temp/trades.json | jq
 
-      - run: yarn prepare:wallet
+      # - run: yarn prepare:wallet
 
-      - name: exit
-        run: |
-          swaps=$(cat temp/trades.json | jq -r '.swaps')
-          if [[ -z "$swaps" || "$swaps" == "0" ]]; then
-            exit 1
-          fi
-        if: always()
+      # - name: exit
+      #   run: |
+      #     swaps=$(cat temp/trades.json | jq -r '.swaps')
+      #     if [[ -z "$swaps" || "$swaps" == "0" ]]; then
+      #       exit 1
+      #     fi
+      #   if: always()
 
-  restart:
-    runs-on: ubuntu-latest
-    needs: start
-    if: success() || failure()
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
+  # restart:
+  #   runs-on: ubuntu-latest
+  #   needs: start
+  #   if: success() || failure()
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v4
 
-      - name: restart
-        run: gh workflow run old-gor.yml
-        if: always()
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+  #     - name: restart
+  #       run: gh workflow run old-gor.yml
+  #       if: always()
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
