Update old-gor.yml

diff --git a/.github/workflows/old-gor.yml b/.github/workflows/old-gor.yml
--- a/.github/workflows/old-gor.yml
+++ b/.github/workflows/old-gor.yml
@@ -73,16 +73,16 @@ jobs:
           fi
         if: always()
 
-  restart:
-    runs-on: ubuntu-latest
-    needs: start
-    if: success() || failure()
-    steps:
-      - name: checkout
-        uses: actions/checkout@v4
+  # restart:
+  #   runs-on: ubuntu-latest
+  #   needs: start
+  #   if: success() || failure()
+  #   steps:
+  #     - name: checkout
+  #       uses: actions/checkout@v4
 
-      - name: restart
-        run: gh workflow run old-gor.yml
-        if: always()
-        env:
-          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+  #     - name: restart
+  #       run: gh workflow run old-gor.yml
+  #       if: always()
+  #       env:
+  #         GH_TOKEN: ${{ secrets.GH_TOKEN }}
